---
title: "Exp analysis - exp144-170 - oracle, random, ucb, parkid on the entire BanditBigMonster series"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(stats)
library(ggplot2)
library(tidyr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")
```


# Paths
```{r, message=FALSE}
data_path <- "~/Code/parkid/data/"
img_path <- "~/Code/parkid/analysis/img/exp144-170/"
dir.create(img_path)
```

# Load data
```{r, message=FALSE, warning=FALSE}
# -------------------------------------------------------------
# User def
num_episodes <- 80
change <- 40
run_codes <- 1:40
num_arms <- 4

exp_names <- c("exp126", # parkid
               "exp128", 
               "exp130", 
               "exp132", 
               "exp134", 
               "exp136", 
               "exp138", 
               "exp140", 
               "exp142", 
               "exp127", # parpar
               "exp129", 
               "exp131", 
               "exp133", 
               "exp135", 
               "exp137", 
               "exp139", 
               "exp141", 
               "exp143", 
               "exp144", # oracle
               "exp145",
               "exp146",
               "exp147",
               "exp148",
               "exp149",
               "exp150",
               "exp151",
               "exp152",
               "exp153", # random
               "exp154",
               "exp155",
               "exp156",
               "exp157",
               "exp158",
               "exp159",
               "exp160",
               "exp161",
               "exp162", # ucb
               "exp163",
               "exp164",
               "exp165",
               "exp166",
               "exp167",
               "exp168",
               "exp169",
               "exp170")

agent_names <- c("ParKid",
                 "ParKid",
                 "ParKid",
                 "ParKid",
                 "ParKid",
                 "ParKid",
                 "ParKid",
                 "ParKid",
                 "ParKid",
                 "ParPar",
                 "ParPar",
                 "ParPar",
                 "ParPar",
                 "ParPar",
                 "ParPar",
                 "ParPar",
                 "ParPar",
                 "ParPar",
                 "Oracle",
                 "Oracle",
                 "Oracle",
                 "Oracle",
                 "Oracle",
                 "Oracle",
                 "Oracle",
                 "Oracle",
                 "Oracle",
                 "Random",
                 "Random",
                 "Random",
                 "Random",
                 "Random",
                 "Random",
                 "Random",
                 "Random",
                 "Random",
                 "UcbUcb",
                 "UcbUcb",
                 "UcbUcb",
                 "UcbUcb",
                 "UcbUcb",
                 "UcbUcb",
                 "UcbUcb",
                 "UcbUcb",
                 "UcbUcb")
                 

task_names <- c("BanditBigMonster2", 
                "BanditBigMonster3", 
                "BanditBigMonster4", 
                "BanditBigMonster5", 
                "BanditBigMonster6", 
                "BanditBigMonster7", 
                "BanditBigMonster8", 
                "BanditBigMonster9", 
                "BanditBigMonster10",
                "BanditBigMonster2", 
                "BanditBigMonster3", 
                "BanditBigMonster4", 
                "BanditBigMonster5", 
                "BanditBigMonster6", 
                "BanditBigMonster7", 
                "BanditBigMonster8", 
                "BanditBigMonster9", 
                "BanditBigMonster10",
                "BanditBigMonster2", 
                "BanditBigMonster3", 
                "BanditBigMonster4", 
                "BanditBigMonster5", 
                "BanditBigMonster6", 
                "BanditBigMonster7", 
                "BanditBigMonster8", 
                "BanditBigMonster9", 
                "BanditBigMonster10",
                "BanditBigMonster2", 
                "BanditBigMonster3", 
                "BanditBigMonster4", 
                "BanditBigMonster5", 
                "BanditBigMonster6", 
                "BanditBigMonster7", 
                "BanditBigMonster8", 
                "BanditBigMonster9", 
                "BanditBigMonster10",
                "BanditBigMonster2", 
                "BanditBigMonster3", 
                "BanditBigMonster4", 
                "BanditBigMonster5", 
                "BanditBigMonster6", 
                "BanditBigMonster7", 
                "BanditBigMonster8", 
                "BanditBigMonster9", 
                "BanditBigMonster10")
                
del_probs <- c("-0.2", 
              "-0.1",
              "0.0",
              "0.1",
              "0.2",
              "0.3",
              "0.4",
              "0.5",
              "0.6",
              "-0.2", 
              "-0.1",
              "0.0",
              "0.1",
              "0.2",
              "0.3",
              "0.4",
              "0.5",
              "0.6",
              "-0.2", 
              "-0.1",
              "0.0",
              "0.1",
              "0.2",
              "0.3",
              "0.4",
              "0.5",
              "0.6",
              "-0.2", 
              "-0.1",
              "0.0",
              "0.1",
              "0.2",
              "0.3",
              "0.4",
              "0.5",
              "0.6",
              "-0.2", 
              "-0.1",
              "0.0",
              "0.1",
              "0.2",
              "0.3",
              "0.4",
              "0.5",
              "0.6")


file_names <- c(
    "par_action",
    "alt_action",
    "alt_policy",
    "kid_action",
    "kid_policy",
    "par_score_E",
    "par_score_R",
    "kid_score_E",
    "kid_score_R",
    "kid_score_H",
    "par_value_E",
    "par_value_R",
    "kid_value_E",
    "kid_value_R",
    "total_R",
    "change_R",
    "total_E",
    "best"
  )

# Init
E_bias <- log(num_arms) * num_arms

# !
results <- NULL
for (i in 1:length(exp_names)) {
  # Get metadata
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  task_name <- task_names[i]
  del_prob <- del_probs[i]
  
  # !
  tmp <- load_result1(exp_name,  run_codes, file_names,
                     n_max = num_episodes + 1)
  
  # Add metadata
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$del_prob <- del_prob
  tmp$num_episodes <- num_episodes
  
  # Join
  results <- bind_rows(results, tmp)
}

results$del_prob <- factor(results$del_prob, levels=c(
    "-0.2", "-0.1", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6"))

```

# Plot - Behave
## Kid
```{r, fig.width=12, fig.height=5}
results %>% 
  filter(agent=="ParKid") %>% 
  filter(run <= 10) %>% 
  ggplot(aes(x=global_step, y=kid_action+1)) +
  geom_point(size=1, alpha=1, color="dodgerblue4") +
  geom_line(aes(x=global_step, y=best+1), size=0.6, alpha=0.5) +
  facet_grid(run~del_prob) +
  labs(x="Time", y="Action", title="Kid (Parkid)") +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) 
```

## Parents (kid anad ucb)
```{r, fig.width=12, fig.height=10}
results %>% 
  filter(agent=="ParKid") %>% 
  filter(run <= 10) %>% 
  ggplot(aes(x=global_step, y=par_action+1)) +
  geom_point(size=1, alpha=1, color="dodgerblue4") +
  geom_line(aes(x=global_step, y=best+1), size=0.6, alpha=0.5) +
  facet_grid(run~del_prob) +
  labs(x="Time", y="Action", title="Parent (Parkid)") +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) -> par1

results %>% 
  filter(agent=="ParPar") %>% 
  filter(run <= 10) %>% 
  ggplot(aes(x=global_step, y=par_action+1)) +
  geom_point(size=1, alpha=1, color="dodgerblue4") +
  geom_line(aes(x=global_step, y=best+1), size=0.6, alpha=0.5) +
  facet_grid(run~del_prob) +
  labs(x="Time", y="Action", title="Parent (Parpar)") +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) -> par2


results %>% 
  filter(agent=="UcbUcb") %>% 
  filter(run <= 10) %>% 
  ggplot(aes(x=global_step, y=par_action+1)) +
  geom_point(size=1, alpha=1, color="palegreen4") +
  geom_line(aes(x=global_step, y=best+1), size=0.6, alpha=0.5) +
  facet_grid(run~del_prob) +
  labs(x="Time", y="Action", title="Parent (UCB)") +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) -> par3

par1 / par2 / par3
```

# Plot - Total rewards
## Scatter w/ median
```{r, fig.width=4, fig.height=7}
results %>% 
  group_by(del_prob, agent, exp, run) %>% 
  summarise(total_R=last(total_R),
            change_R=last(change_R)) %>% 
  ungroup() -> tmp

tmp %>% 
  ggplot(aes(x=del_prob, y=total_R, color=agent)) +
  geom_jitter(width=0.2, size=0.2, alpha=.3) +
  stat_summary(fun=median, geom="point", shape=95, size=10) +
  scale_colour_manual("", values = c(
    "black", "dodgerblue4", "grey", "mediumpurple3")) +
  theme_classic() +
  labs(x="Relative change", y="Total reward", tag="") -> p1

tmp %>% 
  ggplot(aes(x=del_prob, y=change_R, color=agent)) +
  geom_jitter(width=0.2, size=0.2, alpha=.3) +
  stat_summary(fun=median, geom="point", shape=95, size=10) +
  scale_colour_manual("", values = c(
    "black", "dodgerblue4", "grey", "mediumpurple3")) +
  theme_classic() +
  labs(x="Relative change", y="After change", tag="") -> p2

p1 / p2 + plot_layout(guides = "collect")
```

## Boxplot
```{r, fig.width=5, fig.height=7}
results %>% 
  group_by(del_prob, agent, exp, run) %>% 
  summarise(total_R=last(total_R),
            change_R=last(change_R)) %>% 
  ungroup() -> tmp

tmp %>% 
  ggplot(aes(x=del_prob, y=total_R, color=agent)) +
  geom_boxplot(width=0.6, size=0.4, alpha=1) +
  theme_classic() +
  scale_colour_manual("", values = c(
    "black", "dodgerblue4", "grey", "mediumpurple3")) +
  lims(y=c(0, 80)) +
  labs(x="Relative change", y="Total reward", tag="") -> p1

tmp %>% 
  ggplot(aes(x=del_prob, y=change_R, color=agent)) +
  geom_boxplot(width=0.6, size=0.4, alpha=1) +
  theme_classic() +
  scale_colour_manual("", values = c(
    "black", "dodgerblue4", "grey", "mediumpurple3")) +
  lims(y=c(0, 45)) +
  labs(x="Relative change", y="After change", tag="") -> p2

p1 / p2 + plot_layout(guides = "collect")
```

```{r, fig.width=6, fig.height=6}
# Replot change only - zoomed
p2
```

## Mean/SD
### Points
```{r, fig.width=4, fig.height=7}
results %>% 
  group_by(del_prob, agent, exp, run) %>% 
  summarise(total_R=last(total_R),
            change_R=last(change_R)) %>% 
  ungroup() -> tmp

tmp %>%
  group_by(del_prob, agent, exp) %>%
  summarise(
          total_sd=sd(total_R, na.rm = TRUE),
          total_R=mean(total_R),
          change_sd=sd(change_R, na.rm = TRUE),  
          change_R=mean(change_R)) %>% 
          
  ungroup() -> tmp

tmp %>% 
  ggplot(aes(x=del_prob, y=total_R, color=agent)) +
  geom_point(size=2) +
  geom_errorbar(aes(ymin=total_R-total_sd, ymax=total_R+total_sd), 
                width=.4, alpha=0.5) +
  theme_classic() +
  scale_colour_manual("", values = c(
    "black", "dodgerblue4", "grey", "mediumpurple3")) +
  lims(y=c(0, 80)) +
  labs(x="Relative change", y="Total reward", tag="") -> p1

tmp %>% 
  ggplot(aes(x=del_prob, y=change_R, color=agent)) +
  geom_point(size=2) +
  geom_errorbar(aes(ymin=change_R-change_sd, ymax=change_R+change_sd), 
                width=.4, alpha=0.5) +
  theme_classic() +
  scale_colour_manual("", values = c(
    "black", "dodgerblue4", "grey", "mediumpurple3")) +
  lims(y=c(0, 45)) +
  labs(x="Relative change", y="After change", tag="") -> p2

p1 / p2 + plot_layout(guides = "collect")
```

```{r, fig.width=6, fig.height=6}
# Replot change only - zoomed
p2
```

### Ribbon
```{r, fig.width=5, fig.height=8}
results %>% 
  group_by(del_prob, agent, exp, run) %>% 
  summarise(total_R=last(total_R),
            change_R=last(change_R)) %>% 
  ungroup() -> tmp

tmp %>%
  group_by(del_prob, agent, exp) %>%
  summarise(
          total_sd=sd(total_R, na.rm = TRUE),
          total_R=mean(total_R),
          change_sd=sd(change_R, na.rm = TRUE),  
          change_R=mean(change_R)) %>% 
          
  ungroup() -> tmp

tmp %>% 
  ggplot(aes(x=del_prob, y=total_R, color=agent, fill=agent, group=agent)) +
  geom_line() +
  geom_ribbon(aes(ymin=total_R-total_sd, ymax=total_R+total_sd), 
              color=NA, alpha=0.2) +
  theme_classic() +
  scale_colour_manual("", values = c(
    "black", "dodgerblue4", "grey", "mediumpurple3")) +
  scale_fill_manual("", values = c(
    "black", "dodgerblue4", "grey", "mediumpurple3")) +
  lims(y=c(20, 65)) +
  labs(x="Relative change", y="Total reward", tag="") -> p1

tmp %>% 
  ggplot(aes(x=del_prob, y=change_R, color=agent, fill=agent, group=agent)) +
  geom_line() +
  geom_ribbon(aes(ymin=change_R-change_sd, ymax=change_R+change_sd),
              color=NA, alpha=0.2) +
  theme_classic() +
  scale_colour_manual("", values = c(
    "black", "dodgerblue4", "grey", "mediumpurple3")) +
  scale_fill_manual("", values = c(
    "black", "dodgerblue4", "grey", "mediumpurple3")) +
  lims(y=c(10, 45)) +
  labs(x="Relative change", y="After change", tag="") -> p2

p1 / p2 + plot_layout(guides = "collect")
```
```{r, fig.width=6, fig.height=6}
# Replot change only - zoomed
p2
```