---
title: "Analyze exps: 3 and 8 (examples of tuned)"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")
```

# Paths
```{r, message=FALSE}
data_path <- "~/Code/parkid/data/"
img_path <- "~/Code/parkid/analysis/img/exp3-8/"
dir.create(img_path)
```

# Fig. Exploration 
## Load exp3-5
```{r, message=FALSE}
# -------------------------------------------------------------
# User def
task_name <- "change_bandits"
num_episodes <- 180
num_arms <- 4

# ---------------
# First set
param_codes <- c(0)
run_codes <- 1:10

exp_names <- c("exp3", "exp4", "exp5")
agent_names <-
  c("Parkid (inspire)",
    "Parkid (share)",
    "Parpar")
file_names <-
  c(
    "par_action",
    "par_policy",
    "alt_action",
    "alt_policy",
    "kid_action",
    "kid_policy",
    "par_score_E",
    "total_R",
    "total_kid_R",
    "change_R",
    "total_G",
    'best',
    'p_opt'
  )

# Init
E_bias <- log(num_arms) * num_arms

# !
results1 <- NULL
for (i in 1:length(exp_names)) {
  # Load
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  tmp <- load_result2(exp_name, param_codes, run_codes, file_names,
                     n_max = num_episodes + 1)
  # Add metadata
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$num_episodes <- num_episodes
  # Join
  results1 <- bind_rows(results1, tmp)
}

# clean
rm(tmp,
   agent_names,
   agent_name,
   E_bias,
   exp_name,
   exp_names,
   file_names,
   i)
```

## Load exp6-8
```{r, message=FALSE}
# -------------------------------------------------------------
# User def
task_name <- "change_bandits"
num_episodes <- 180
num_arms <- 4

# ---------------
# First set
param_codes <- 0:9
run_codes <- c(1)

exp_names <- c("exp6", "exp7", "exp8")
agent_names <-
  c("Parkid (inspire)",
    "Parkid (share)",
    "Parpar")
file_names <-
  c(
    "par_action",
    "par_policy",
    "alt_action",
    "alt_policy",
    "kid_action",
    "kid_policy",
    "par_score_E",
    "total_R",
    "total_kid_R",
    "change_R",
    "total_G",
    'best',
    'p_opt'
  )

# Init
E_bias <- log(num_arms) * num_arms

# !
results2 <- NULL
for (i in 1:length(exp_names)) {
  # Load
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  tmp <- load_result2(exp_name, param_codes, run_codes, file_names,
                     n_max = num_episodes + 1)
  # Add metadata
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$num_episodes <- num_episodes
  # Join
  results2 <- bind_rows(results2, tmp)
}

# clean
rm(tmp,
   agent_names,
   agent_name,
   E_bias,
   exp_name,
   exp_names,
   file_names,
   i)
```

# Rewards
```{r, fig.width=2.5, fig.height=1}
results1 %>% 
  group_by(agent, exp, run) %>% 
  summarise(total_R=last(total_R),
            change_R=last(change_R),
            total_G=last(total_G)) %>% 
  ungroup() -> tmp

tmp %>% 
  ggplot(aes(x=agent, y=total_R)) +
  geom_boxplot(width=0.4, color="red") +
  geom_jitter(color="black", width = 0.4, alpha=0.4, size=0.6) +
  theme_classic2() +
  labs(x="", y="Total reward (R)", title="Total")  +
  coord_flip() -> p1

tmp %>% 
  ggplot(aes(x=agent, y=change_R)) +
  geom_boxplot(width=0.4, color="red") +
  geom_jitter(color="black", width = 0.4, alpha=0.4, size=0.6) +
  theme_classic2() +
  labs(x="", y="Total reward (R)", title="After") + 
  coord_flip() -> p2

p <- p1 + p2 + plot_annotation(title = "Exp3-5")
print(p)

name <- paste(img_path, "exp3-5-total_R", sep="")
ggsave(paste(name, ".png", sep=""))
```
```{r, fig.width=2.5, fig.height=1}
results2 %>% 
  group_by(agent, exp, run, param) %>% 
  summarise(total_R=last(total_R),
            change_R=last(change_R),
            total_G=last(total_G)) %>% 
  ungroup() -> tmp

tmp %>% 
  ggplot(aes(x=agent, y=total_R)) +
  geom_boxplot(width=0.4, color="red") +
  geom_jitter(color="black", width = 0.4, alpha=0.4, size=0.6) +
  theme_classic2() +
  labs(x="", y="Total reward (R)", title="Total")  +
  coord_flip() -> p1

tmp %>% 
  ggplot(aes(x=agent, y=change_R)) +
  geom_boxplot(width=0.4, color="red") +
  geom_jitter(color="black", width = 0.4, alpha=0.4, size=0.6) +
  theme_classic2() +
  labs(x="", y="Total reward (R)", title="After") + 
  coord_flip() -> p2

p <- p1 + p2 + plot_annotation(title = "Exp6-8")
print(p)

name <- paste(img_path, "exp6-8-total_R", sep="")
ggsave(paste(name, ".png", sep=""))
```

```{r, fig.width=2.6, fig.height=1}
results1 %>% 
  filter(exp == "exp3") %>% 
  filter(global_step > 20) %>%
  ggplot(aes(x=global_step, y=total_R /2 / global_step, group=run)) +
  geom_line(size=0.6, color="red") +
  geom_line(aes(x=global_step, y=p_opt), color="red", linetype = "dashed") +
  theme_classic2() +
  # lims(y=c(0, 1)) +
  labs(x="Episodes", y="Reward", title="Parkid (inspire)") -> p1

results1 %>% 
  filter(exp == "exp4") %>% 
  filter(global_step > 20) %>%
  ggplot(aes(x=global_step, y=total_R /2/ global_step, group=run)) +
  geom_line(size=0.6, color="red") +
  geom_line(aes(x=global_step, y=p_opt), color="red", linetype = "dashed") +
  theme_classic2() +
  # lims(y=c(0, 1)) +
  labs(x="Episodes", y="Reward", title="2Par") -> p2

p <- p1 + p2
print(p)
name <- paste(img_path, "time_R", sep="")
ggsave(paste(name, ".png", sep=""))
```

# Actions
## Exp 1-2 (par only)
```{r, fig.width=3, fig.height=3.5}
results1 %>% 
  filter(exp == "exp3") %>% 
  ggplot(aes(x=global_step, y=par_action + 1)) +
  geom_point(alpha=0.8, size=0.6) +
  geom_line(aes(x=global_step, y=best + 1), color="red", linetype = "dashed") +
  facet_wrap(run~., ncol=1) +
  scale_y_continuous(limits=c(0.9, num_arms+.1), breaks = c(1, 4)) +
  theme(panel.spacing = unit(.2, "lines")) +
  theme_classic2() +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank()
  ) +
  labs(x="Episode", y="Arm", title="Parkid (inspire)") -> p1

results1 %>% 
  filter(exp == "exp4") %>% 
  ggplot(aes(x=global_step, y=par_action + 1)) +
  geom_point(alpha=0.8, size=0.6) +
  geom_line(aes(x=global_step, y=best + 1), color="red", linetype = "dashed") +
  facet_wrap(run~., ncol=1) +
  scale_y_continuous(limits=c(0.9, num_arms+.1), breaks = c(1, 4)) +
  theme(panel.spacing = unit(.2, "lines")) +
  theme_classic2() +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank()
  ) +
  labs(x="Episode", y="Arm", title="Parkid (share)") -> p2


results1 %>% 
  filter(exp == "exp5") %>% 
  ggplot(aes(x=global_step, y=par_action + 1)) +
  geom_point(alpha=0.8, size=0.6) +
  geom_line(aes(x=global_step, y=best + 1), color="red", linetype = "dashed") +
  facet_wrap(run~., ncol=1) +
  scale_y_continuous(limits=c(0.9, num_arms+.1), breaks = c(1, 4)) +
  theme(panel.spacing = unit(.2, "lines")) +
  theme_classic2() +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank()
  ) +
  labs(x="Episode", y="Arm", title="2Par (single)") -> p3

p <- p1 + p2 + p3
print(p)
name <- paste(img_path, "behave_par", sep="")
ggsave(paste(name, ".png", sep=""), plot=p, width = 1*2, height = 3.5*2)

```

## Exp 1 - par and kid seperate
```{r, fig.width=2, fig.height=3.5}
results1 %>% 
  filter(exp == "exp4") %>% 
  # ggplot(aes(x=global_step, y=par_action + 1, color=factor(par_policy))) +
  ggplot(aes(x=global_step, y=par_action + 1)) +
  geom_point(alpha=0.8, size=0.6) +
  geom_line(aes(x=global_step, y=best + 1), color="red", linetype = "dashed") +
  facet_wrap(run~., ncol=1) +
  scale_y_continuous(limits=c(0.9, num_arms+.1), breaks = c(1, 4)) +
  theme(panel.spacing = unit(.2, "lines")) +
  theme_classic2() +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    legend.position = "none"
  ) +
  # scale_colour_manual("Policy", values=c("orchid4", "grey1")) +
  labs(x="Episode", y="Arm", title="Par") -> p1

results1 %>% 
  filter(exp == "exp4") %>% 
  ggplot(aes(x=global_step, y=kid_action + 1)) +
  # ggplot(aes(x=global_step, y=kid_action + 1, color=factor(kid_policy))) +
  geom_point(alpha=0.8, size=0.6) +
  geom_line(aes(x=global_step, y=best + 1), color="red", linetype = "dashed") +
  facet_wrap(run~., ncol=1) +
  scale_y_continuous(limits=c(0.9, num_arms+.1), breaks = c(1, 4)) +
  theme(panel.spacing = unit(.2, "lines")) +
  theme_classic2() +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank()
  ) +
  # scale_colour_manual("Policy", values=c("orchid4", "grey1")) +
  labs(x="Episode", y="Arm", title="Kid") -> p2

p <- p1 + p2
print(p)

name <- paste(img_path, "behave_parkid", sep="")
ggsave(paste(name, ".png", sep=""))
```
