---
title: "Task payouts - illustration"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
# library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")

# --- Main path to all data ---
data_path <- "/Volumes/Data/infomercial/data"
```

# Task 1
```{r, fig.width=4, fig.height=1.5}
best <- 1
best_choice = rep(0, 4)
best_choice[best] <- 1

classic <- data.frame(
  best=best_choice,
  choice=1:4,
  payout=c(6, 2, 3, 1))

# Result
classic %>% 
  ggplot(aes(x=1, y=payout, fill=factor(best))) + 
  geom_bar(width=0.5, alpha=1, stat="identity") +
  lims(x=c(0, 2)) +
  scale_y_continuous(limits=c(0,8.1), breaks = c(0, 8)) +
  scale_fill_manual(values=c("darkgrey", "black")) +
  labs(x="Action", y="Reward\nvalue", subtitle="Beginning (40 trials)") +
  facet_wrap(choice~., nrow=1) +
  theme_classic() +
  theme(legend.position = "none") +
  # theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.x = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p1

p1
```

## change
```{r, fig.width=4, fig.height=1.5}
best <- 4
best_choice = rep(0, 4)
best_choice[best] <- 1

classic <- data.frame(
  best=best_choice,
  choice=1:4,
  payout=c(6, 2, 3, 8))

# Result
classic %>% 
  ggplot(aes(x=1, y=payout, fill=factor(best))) + 
  geom_bar(width=0.5, alpha=1, stat="identity") +
  lims(x=c(0, 2)) +
  scale_y_continuous(limits=c(0,8.1), breaks = c(0, 8)) +
  scale_fill_manual(values=c("darkgrey", "black")) +
  labs(x="Action", y="Reward\nvalue", subtitle="After change (40 trials)") +
  facet_wrap(choice~., nrow=1) +
  theme_classic() +
  # theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(legend.position = "none") +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.x = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p2

p2
```

```{r, fig.width=4, fig.height=3}
p1 / p2 + 
  plot_annotation(title="Monsters task (deterministic)")
```

# Task 2 - Variable monsters
```{r, fig.width=4, fig.height=1.5}
best <- 1
best_choice = rep(0, 4)
best_choice[best] <- 1

classic <- data.frame(
  best=best_choice,
  choice=1:4,
  payout=c(0.4, 0.2, 0.3, 0.1))

# Result
classic %>% 
  ggplot(aes(x=1, y=payout, fill=factor(best))) + 
  geom_bar(width=0.5, alpha=1, stat="identity") +
  lims(x=c(0, 2)) +
  scale_y_continuous(limits=c(0,1.1), breaks = c(0, 1)) +
  scale_fill_manual(values=c("darkgrey", "black")) +
  labs(x="Action", y="Reward\nvalue", subtitle="Beginning (40 trials)") +
  facet_wrap(choice~., nrow=1) +
  theme_classic() +
  theme(legend.position = "none") +
  # theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(axis.text.x = element_blank()) +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.x = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p1

p1
```

## change
```{r, fig.width=4, fig.height=1.5}
best <- 4
best_choice = rep(0, 4)
best_choice[best] <- 1

classic <- data.frame(
  best=best_choice,
  choice=1:4,
  payout=c(0.4, 0.2, 0.3, 0.8))

# Result
classic %>% 
  ggplot(aes(x=1, y=payout, fill=factor(best))) + 
  geom_bar(width=0.5, alpha=1, stat="identity") +
  lims(x=c(0, 2)) +
  scale_y_continuous(limits=c(0,1.1), breaks = c(0, 1)) +
  scale_fill_manual(values=c("darkgrey", "black")) +
  labs(x="Action", y="Reward\nvalue", subtitle="After change (40 trials)") +
  facet_wrap(choice~., nrow=1) +
  theme_classic() +
  # theme_pubr(base_size = 6, legend = "none") +
  theme(strip.background = element_blank()) +
  theme(axis.text.x = element_blank()) +
  theme(legend.position = "none") +
  # theme(axis.text.y = element_blank()) +
  theme(axis.ticks.x = element_blank()) +
  theme(strip.text = element_blank()) +
  theme(axis.line = element_blank()) +
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) -> p2

p2
```

```{r, fig.width=4, fig.height=3}
p1 / p2 + 
  plot_annotation(title="Variable monsters task (probabilistic)")
```