---
title: "Test exps analysis"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(tidyr)
# library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")
```


# Paths
```{r, message=FALSE}
data_path <- "~/Code/parkid/data/"
img_path <- "~/Code/parkid/analysis/img/test/"
dir.create(img_path)
```


# Load data
```{r, message=FALSE, warning=FALSE}
# -------------------------------------------------------------
# User def
task_name <- "change_bandits"
num_episodes <- 80
change <- 40
run_codes <- 1:100
num_arms <- 4

exp_names <- c("test1", "test2", "test3", "test4")
agent_names <- c("ParKid", "ParPar", "UcbUcb", "Oracle")
file_names <-
  c(
    "par_action",
    "par_policy",
    "alt_action",
    "alt_policy",
    "kid_action",
    "kid_policy",
    "par_score_E",
    "par_score_R",
    "par_bonus",
    "kid_score_E",
    "kid_score_R",
    "par_value_E",
    "par_value_R",
    "kid_value_E",
    "kid_value_R",
    "total_R",
    "change_R",
    "total_E",
    "total_G",
    'best',
    'p_opt'
  )

# -------------------------------------------------------------
# !
results <- NULL
for (i in 1:length(exp_names)) {
  # Load
  exp_name <- exp_names[i]
  agent_name <- agent_names[i]
  tmp <- load_result1(exp_name,  run_codes, file_names,
                     n_max = num_episodes + 1)
  
  # Add metadata
  tmp$exp <- exp_name
  tmp$agent <- agent_name
  tmp$task <- task_name
  tmp$num_episodes <- num_episodes
  
  # Join
  results <- bind_rows(results, tmp)
}
```

# Plot - Behave
## Kid
```{r, fig.width=3, fig.height=5}
results %>% 
  filter(agent=="ParKid") %>% 
  filter(run <= 10) %>% 
  ggplot(aes(x=global_step, y=kid_action+1)) +
  geom_point(size=1, alpha=1, color="dodgerblue4") +
  geom_line(aes(x=global_step, y=best+1), size=0.6, alpha=0.5) +
  facet_grid(run~.) +
  labs(x="Time", y="Action", title="Kid (Parkid)") +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) 
```

## Parents 
```{r, fig.width=6, fig.height=5}
results %>% 
  filter(agent=="ParKid") %>% 
  filter(run <= 10) %>% 
  ggplot(aes(x=global_step, y=par_action+1)) +
  geom_point(size=1, alpha=1, color="dodgerblue4") +
  geom_line(aes(x=global_step, y=best+1), size=0.6, alpha=0.5) +
  facet_grid(run~.) +
  labs(x="Time", y="Action", title="Parent (Parkid)") +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) -> par1

results %>% 
  filter(agent=="ParPar") %>% 
  filter(run <= 10) %>% 
  ggplot(aes(x=global_step, y=par_action+1)) +
  geom_point(size=1, alpha=1, color="palegreen4") +
  geom_line(aes(x=global_step, y=best+1), size=0.6, alpha=0.5) +
  facet_grid(run~.) +
  labs(x="Time", y="Action", title="Parent (ParPar)") +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) -> par2

results %>% 
  filter(agent=="UcbUcb") %>% 
  filter(run <= 10) %>% 
  ggplot(aes(x=global_step, y=par_action+1)) +
  geom_point(size=1, alpha=1, color="mediumpurple3") +
  geom_line(aes(x=global_step, y=best+1), size=0.6, alpha=0.5) +
  facet_grid(run~.) +
  labs(x="Time", y="Action", title="Parent (UCB)") +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) -> par3

# ---
par1 + par2 + par3
```
# Plot - Value timecourses
## Reward (no ucb)
```{r, fig.width=5, fig.height=3}
results %>% 
  filter(agent=="ParKid") %>% 
  filter(run <= 5) %>% 
  ggplot(aes(x=global_step, y=kid_value_R)) +
  geom_point(size=1, alpha=1, color="dodgerblue3") +
  facet_grid(run~agent) +
  labs(x="Time", y="Reward value", title="Kid") +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) -> kid1

results %>% 
  filter(agent!="UcbUcb") %>% 
  filter(agent!="Oracle") %>% 
  filter(run <= 5) %>% 
  ggplot(aes(x=global_step, y=par_value_R)) +
  geom_point(size=1, alpha=1, color="gray27") +
  facet_grid(run~agent) +
  labs(x="Time", y="Reward value", title="Parent") +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) -> par1

kid1 + par1 + plot_layout(ncol = 2, widths = c(1, 2))
```

## Info val (no ucb)
```{r, fig.width=5, fig.height=3}
results %>% 
  filter(agent=="ParKid") %>% 
  filter(run <= 5) %>% 
  ggplot(aes(x=global_step, y=kid_value_E)) +
  geom_point(size=1, alpha=1, color="dodgerblue3") +
  facet_grid(run~agent) +
  labs(x="Time", y="Info value", title="Kid") +
  scale_y_continuous(trans='log10') +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) -> kid1

results %>% 
  filter(agent!="UcbUcb") %>% 
  filter(run <= 5) %>% 
  ggplot(aes(x=global_step, y=par_value_E)) +
  geom_point(size=1, alpha=1, color="gray27") +
  facet_grid(run~agent) +
  labs(x="Time", y="Info value", title="Parent") +
  scale_y_continuous(trans='log10') +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) -> par1

kid1 + par1 + plot_layout(ncol = 2, widths = c(1, 2))
```
# Plot - bonus (ucb)
```{r, fig.width=3, fig.height=7}
results %>% 
  filter(agent == "UcbUcb") %>% 
  filter(run <= 10) %>% 
  ggplot(aes(x=global_step, y=par_bonus)) +
  geom_point(size=1, alpha=1, color="mediumpurple3") +
  geom_hline(yintercept=1, color="black", size=.1) +
  facet_grid(run~agent) +
  labs(x="Time", y="Count bonus", title="Ucb") +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) -> ucb1
ucb1
```


# Plot - Total rewards
## Scatter w/ median
```{r, fig.width=4, fig.height=7}
results %>% 
  group_by(agent, exp, run) %>% 
  summarise(total_R=last(total_R),
            change_R=last(change_R)) %>% 
  ungroup() -> tmp

tmp %>% 
  ggplot(aes(x=agent, y=total_R, color=agent)) +
  geom_jitter(width=0.1, size=0.4, alpha=.3) +
  stat_summary(fun=median, geom="point", shape=95, size=10) +
  scale_colour_manual("", values = c(
    "grey", "dodgerblue4", "palegreen4", "mediumpurple3")) +
  theme_classic() +
  lims(y=c(0, 80)) +
  labs(x="", y="Total reward", tag="") -> p1

tmp %>% 
  ggplot(aes(x=agent, y=change_R, color=agent)) +
  geom_jitter(width=0.1, size=0.4, alpha=.3) +
  stat_summary(fun=median, geom="point", shape=95, size=10) +
  scale_colour_manual("", values = c(
    "grey", "dodgerblue4", "palegreen4", "mediumpurple3")) +
  theme_classic() +
  lims(y=c(0, 80)) +
  labs(x="", y="After change", tag="") -> p2

p1 / p2 + plot_layout(guides = "collect")
```
