---
title: "Tune 26-27 : parkid v parpar - broad sweeps, on Bandit...Monster4"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(tidyr)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")
```

# Paths
```{r, message=FALSE}
data_path <- "~/Code/parkid/data/"
img_path <- "~/Code/parkid/analysis/img/tune26-27/"
dir.create(img_path)
```

# Load
```{r, message=FALSE}
# -------------------------------------------------------------
num_episodes <- 120

# The overestimate due to E0
num_arms <- 4
agent_names <- c("ParKid", "ParPar")

rank_names1 <- c(
  "tune26_sorted.csv",
  "tune27_sorted.csv"
)
result1 <- NULL
for (i in 1:length(rank_names1)) {
  rank_name <- rank_names1[i]
  agent_name <- agent_names[i]
  
  tmp <- read_csv(paste(data_path, rank_name, sep = "/"))
  tmp$exp <- rank_name
  tmp$agent <- agent_name
  result1 <- bind_rows(result1, tmp)
}
result1$agent <- factor(result1$agent, levels = agent_names)
```

# Result 1
## Ranked ribbon
```{r, fig.width=2.5, fig.height=1.2}
result1 %>%
  # filter(index < 25) %>%
  ggplot(aes(x = index, y = total_R, color = agent)) +
  geom_point(size = 0.6, alpha = 0.6) +
  geom_ribbon(
    aes(
      ymin = total_R - mad_total_R,
      ymax = total_R + mad_total_R,
      fill = agent,
      group = agent
    ),
    alpha = 0.1,
    color = NA
  ) +
  geom_line(size = 1, alpha = 1) +
  theme_classic2() +
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  # lims(y=c(0, 100)) +
  scale_color_manual(
    "",
    values = c(
      "mediumpurple4",
      "steelblue4"
    )
    ) +
  scale_fill_manual(
    "",
    values = c(
      "mediumpurple4",
      "steelblue4"
    )
    ) +
      labs(x = "Rank", y = "Reward (R)")

```
## par boredomw ribbon
```{r, fig.width=2.5, fig.height=1.2}
result1 %>%
  # filter(index < 25) %>%
  ggplot(aes(x = par_boredom, y = total_R, color = agent)) +
  geom_point(size = 0.6, alpha = 0.6) +
  geom_ribbon(
    aes(
      ymin = total_R - mad_total_R,
      ymax = total_R + mad_total_R,
      fill = agent,
      group = agent
    ),
    alpha = 0.1,
    color = NA
  ) +
  geom_line(size = 1, alpha = 1) +
  theme_classic2() +
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  # lims(y=c(0, 100)) +
  scale_color_manual(
    "",
    values = c(
      "mediumpurple4",
      "steelblue4"
    )
    ) +
  scale_fill_manual(
    "",
    values = c(
      "mediumpurple4",
      "steelblue4"
    )
    ) +
      labs(x = "Parent bordom", y = "Reward (R)") 
```

## kid_scale ribbon
```{r, fig.width=2.5, fig.height=1.2}
result1 %>%
  # filter(index < 25) %>%
  ggplot(aes(x = kid_scale, y = total_R, color = agent)) +
  geom_point(size = 0.6, alpha = 0.6) +
  geom_ribbon(
    aes(
      ymin = total_R - mad_total_R,
      ymax = total_R + mad_total_R,
      fill = agent,
      group = agent
    ),
    alpha = 0.1,
    color = NA
  ) +
  geom_line(size = 1, alpha = 1) +
  theme_classic2() +
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  # lims(y=c(0, 100)) +
  scale_color_manual(
    "",
    values = c(
      "mediumpurple4",
      "steelblue4"
    )
    ) +
  scale_fill_manual(
    "",
    values = c(
      "mediumpurple4",
      "steelblue4"
    )
    ) +
      labs(x = "Kid scale", y = "Reward (R)")
```

## Density
```{r, fig.width=2.5, fig.height=1.2}
result1 %>%
  ggplot(aes(x=total_R, fill=agent, color=agent)) +
  geom_density(alpha=0.4) +
  theme_classic2() +
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  scale_color_manual(
    "",
    values = c(
      "mediumpurple4",
      "steelblue4"
    )
    ) +
  scale_fill_manual(
    "",
    values = c(
      "mediumpurple4",
      "steelblue4"
  )) 
  # lims(x=c(60, 120)) 
  # facet_grid(.~agent)
```

## Hist
```{r, fig.width=1.4, fig.height=1.2}
result1 %>%
  ggplot(aes(x=total_R, fill=agent, color=agent)) +
  geom_histogram(alpha=1, bins=60) +
  theme_classic2() +
  theme(strip.background = element_blank(),
        strip.text.y = element_blank()) +
  scale_color_manual(
    "",
    values = c(
      "mediumpurple4",
      "steelblue4"
    )
    ) +
  scale_fill_manual(
    "",
    values = c(
      "mediumpurple4",
      "steelblue4"
  )) +
  labs(x="Total reward", y="Count", title="All models") +
  facet_grid(agent~.)
```

