---
title: "Tune 28-33 : parkid v parpar v ucb - 10x sweeps (on BanditBigMonster10)"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(tidyr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")
```

# Paths
```{r, message=FALSE}
data_path <- "~/Code/parkid/data/"
analysis_path <- "~/Code/parkid/analysis/"
img_path <- "~/Code/parkid/analysis/img/tune28-33/"
dir.create(img_path)
```

# Load
```{r, message=FALSE}
# -------------------------------------------------------------
num_episodes <- 120

# The overestimate due to E0
num_arms <- 4
agent_names <- c("ParKid", 
                 "ParKid (gate)", 
                 "ParKid (gate/scale)", 
                 "ParPar", 
                 "UcbUcb (beta only)", 
                 "UcbUcb")

rank_names1 <- c(
  "tune28_sorted.csv",
  "tune29_sorted.csv",
  "tune30_sorted.csv",
  "tune31_sorted.csv",
  "tune32_sorted.csv",
  "tune33_sorted.csv"
)

tuned <- NULL
for (i in 1:length(rank_names1)) {
  # Select names
  rank_name <- rank_names1[i]
  agent_name <- agent_names[i]
  
  # Load
  tmp <- read_csv(paste(data_path, rank_name, sep = "/"), 
                  show_col_types = FALSE)
  
  # Add metadata
  tmp$exp <- rank_name
  tmp$agent <- agent_name
  tuned <- bind_rows(tuned, tmp)
}

# Order
tuned$agent <- factor(tuned$agent, levels = agent_names)
```

# Result 
## Ranked ribbon (all)
```{r, fig.width=8, fig.height=3}
tuned %>%
  # filter(index < 25) %>%
  ggplot(aes(x = index, y = total_R, color = agent)) +
  geom_point(size = 0.6, alpha = 0.6) +
  geom_ribbon(
    aes(
      ymin = total_R - std_total_R,
      ymax = total_R + std_total_R,
      fill = agent,
      group = agent
    ),
    alpha = 0.1,
    color = NA
  ) +
  geom_line(size = 1, alpha = 1) +
  facet_grid(.~agent) +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  scale_color_manual("", values = c(
    "dodgerblue4", "dodgerblue3", "dodgerblue2", "mediumpurple3", "palegreen4", "palegreen3")) +
  scale_fill_manual("", values = c(
    "dodgerblue4", "dodgerblue3", "dodgerblue2", "mediumpurple3", "palegreen4", "palegreen3")) +
  labs(x = "Rank", y = "Reward (R)")

```

## Ranked ribbon (select)
```{r, fig.width=8, fig.height=3}
tuned %>%
  filter(agent %in% c("ParKid", "ParPar", "UcbUcb")) %>% 
  ggplot(aes(x = index, y = total_R, color = agent)) +
  geom_point(size = 0.6, alpha = 0.6) +
  geom_ribbon(
    aes(
      ymin = total_R - std_total_R,
      ymax = total_R + std_total_R,
      fill = agent,
      group = agent
    ),
    alpha = 0.1,
    color = NA
  ) +
  geom_line(size = 1, alpha = 1) +
  facet_grid(.~agent) +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  scale_color_manual("", values = c(
    "dodgerblue4", "mediumpurple3", "palegreen4")) +
  scale_fill_manual("", values = c(
    "dodgerblue4", "mediumpurple3", "palegreen4")) +
  labs(x = "Model rank", y = "Total reward", subtitle="Relative change: 0.6")
  
```

# Save data
```{r}
save.image(paste(analysis_path, "tune28-33.RData", sep=""))
```