---
title: "Tune 11-13 : parkid versus twopar (homeo and sharing - test2)"
output: html_notebook
---

# Library
```{r, message=FALSE}
library(zoo)
library(ggplot2)
library(tidyr)
library(ggpubr)
library(patchwork)
library(tidyr)
library(dplyr)
library(gridExtra)
library(grid)
library(readr)
library(latex2exp)
# library(MASS) 
library(scales)
library(patchwork)
options(scipen=1000000)

# Load load_result and other helpful functions
source("utils.R")
```

# Paths
```{r, message=FALSE}
data_path <- "~/Code/parkid/data/"
img_path <- "~/Code/parkid/analysis/img/tune11-13/"
dir.create(img_path)
```

# Load
```{r, message=FALSE}
# -------------------------------------------------------------
num_episodes <- 2420

# The overestimate due to E0
num_arms <- 121

rank_names <- c("tune11_sorted.csv",
                "tune12_sorted.csv",
                "tune13_sorted.csv")
agent_names <- c("parkid",
                 "parkid (share)",
                 "twopar")

result <- NULL
for (i in 1:length(rank_names)) {
  rank_name <- rank_names[i]
  agent_name <- agent_names[i]
  
  tmp <- read_csv(paste(data_path, rank_name, sep = "/"))
  tmp$exp <- rank_name
  tmp$agent <- agent_name
  
  result <- bind_rows(result, tmp)
}

result$agent <- factor(result$agent, levels = agent_names)
```

# Plot ranked
```{r, fig.width=2.6, fig.height=1}
result %>% 
  filter(index < 20) %>%
  ggplot(aes(x=index, y=change_R, color=agent)) +
  geom_point(size=0.6, alpha=0.6) +
  geom_line(size=0.6, alpha=0.6) +
  theme_classic2() +
  theme(legend.position = "none")+
  scale_color_manual("", values = c("mediumpurple3", "mediumpurple4", "lightsteelblue4")) +
  labs(x="Rank", y="Reward (R)") -> p1

result %>% 
  # filter(index < 100) %>%
  ggplot(aes(x=index, y=change_R, color=agent)) +
  geom_point(size=0.6, alpha=0.6) +
  geom_line(size=0.6, alpha=0.6) +
  theme_classic2() +
  # lims(y=c(20, 40)) +
  scale_color_manual("", values = c("mediumpurple3", "mediumpurple4", "lightsteelblue4")) +
  labs(x="Rank", y="Reward (R)") -> p2

p1 + p2
```

# Plot boredom
## By model
```{r, fig.width=2.3, fig.height=0.8}
result %>% 
  ggplot(aes(x=log10(par_boredom), y=change_R, color=agent)) +
  geom_point(size=0.6, alpha=0.4) +
  geom_smooth(span = 0.4) +
  theme_classic2() +
  facet_grid(.~agent) +
    theme(
    strip.background = element_blank(),
    strip.text.x = element_blank()
  ) +
  scale_color_manual("", values = c("mediumpurple3", "mediumpurple4", "lightsteelblue4")) +
  labs(x="Parent boredom", y="Reward (R)") 
```

## Compare models
```{r, fig.width=1.6, fig.height=0.8}
result %>% 
  ggplot(aes(x=log10(par_boredom), y=change_R, color=agent)) +
  geom_smooth(span = 0.4, se=FALSE) +
  theme_classic2() +
    theme(
    strip.background = element_blank(),
    strip.text.x = element_blank()
  ) +
  scale_color_manual("", values = c("mediumpurple3", "mediumpurple4", "lightsteelblue4")) +
  labs(x="Parent boredom", y="Reward (R)") 
```
# Other params
```{r, fig.width=4, fig.height=1.2}
result %>% 
  filter(agent == "parkid (share)") %>% 
  ggplot(aes(x=log10(par_boredom), y=change_R, color=log10(par_boredom))) +
  geom_point(size=1, alpha=0.9) +
  geom_smooth(span = 0.4, color="black") +
  theme_classic2() +
  facet_grid(.~agent) +
    theme(
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    legend.position = "none"
  ) +
  labs(x="Par boredom", y="Reward (R)", title="parkid (shared)") -> p1

result %>% 
  filter(agent == "parkid (share)") %>% 
  ggplot(aes(x=set_point, y=change_R, color=log10(par_boredom))) +
  geom_point(size=1, alpha=0.9) +
  geom_smooth(span = 0.4, color="black") +
  theme_classic2() +
  facet_grid(.~agent) +
    theme(
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    legend.position = "none"
  ) +
  scale_color_continuous("Par boredom") +
  labs(x="Set point", y="Reward (R)") -> p2

result %>% 
  filter(agent == "parkid (share)") %>% 
  ggplot(aes(x=share, y=change_R, color=log10(par_boredom))) +
  geom_point(size=1, alpha=0.9) +
  geom_smooth(span = 0.4, color="black") +
  theme_classic2() +
  facet_grid(.~agent) +
    theme(
    strip.background = element_blank(),
    strip.text.x = element_blank()
  ) +
  scale_color_continuous("Par boredom") +
  labs(x="Share", y="Reward (R)") -> p3

p1 + p2 + p3
```
